#!/bin/bash

# FinanceFlow - Supabase Setup Script
# This script starts Supabase, extracts credentials, and updates .env.local

set -e

echo "🚀 Starting Supabase..."
echo ""

# Start Supabase and capture output
SUPABASE_OUTPUT=$(supabase start 2>&1)

# Check if start was successful
if [ $? -ne 0 ]; then
  echo "❌ Failed to start Supabase"
  echo "$SUPABASE_OUTPUT"
  exit 1
fi

echo "$SUPABASE_OUTPUT"
echo ""

# Extract credentials from output
API_URL=$(echo "$SUPABASE_OUTPUT" | grep "API URL:" | awk '{print $3}')
ANON_KEY=$(echo "$SUPABASE_OUTPUT" | grep "anon key:" | awk '{print $3}')
SERVICE_KEY=$(echo "$SUPABASE_OUTPUT" | grep "service_role key:" | awk '{print $3}')
DB_URL=$(echo "$SUPABASE_OUTPUT" | grep "DB URL:" | awk '{print $3}')
STUDIO_URL=$(echo "$SUPABASE_OUTPUT" | grep "Studio URL:" | awk '{print $3}')

# Update .env.local
echo "📝 Updating .env.local with credentials..."

cat > .env.local << EOF
# FinanceFlow Environment Variables
# Auto-generated by setup-supabase.sh

# Supabase Configuration (Local Development)
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

# Application Configuration
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Database URL (for Supabase CLI)
DATABASE_URL=$DB_URL
EOF

echo "✅ .env.local updated successfully!"
echo ""

# Apply migrations
echo "📦 Applying database migrations..."
supabase db reset --no-seed

echo ""
echo "🌱 Running seed data..."
supabase db reset

echo ""
echo "🎨 Generating TypeScript types..."
supabase gen types typescript --local > src/types/database.types.ts

echo ""
echo "✅ Setup complete!"
echo ""
echo "📊 Supabase Studio: $STUDIO_URL"
echo "🔗 API URL: $API_URL"
echo ""
echo "Next steps:"
echo "1. Open Supabase Studio and create a test user"
echo "2. Run: npm run dev"
echo "3. Start building! 🎉"